server:
  port: 8888

coffeenet:
  application-name: 'CoffeeNet Config Server'
  profile: development
  logging:
    console:
      enabled: true

config-server:
  resource:
    id: 'config'

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/user

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: file:./configs
          clone-on-start: true
          search-paths: '{application}/{profile}'
