server:
  port: 8888

coffeenet:
  application-name: CoffeeNet Config Server
  allowed-authorities: ROLE_COFFFEENET-ADMIN
  profile: development
  logging:
    console:
      enabled: true

spring:
  profiles:
    active: vault, git
  cloud:
    config:
      server:
        git:
          order: 1
          uri: file:./configs
          clone-on-start: true
          search-paths: '{application}/{profile}'
        vault:
          order: 0